### ISSUE TITLE
Versioned configs

### ISSUE THREAD

**Issue by Hacksore** [harshkhandeparkar/tauri-settings#10]
This looks like a neat lib but I have a small question about configuration and extensibility. 

How would you handle a config that was initially setup say for version `1.0.0`.

```json
{
  "theme": "light"
}
```

Then in version `2.0.0` you add a new config option say `telemetry`. How would you expand the config to keep it backwards compatible?

I've seen something in zustand that solves this problem when persiting local storage by allowing versions numbers and migrations to exists. Would that besomething that should be added to this lib?

https://docs.pmnd.rs/zustand/integrations/persisting-store-data

Happy to hear thoughts on this as I'm actively considering switching to this for [Overlayed](https://overlayed.dev).

**Comment by harshkhandeparkar** [comment]
Hi @Hacksore! That is a nice feature request, but I am not sure how to best implement this yet.

The library does handle defaults in the `SettingsManager` class, though. A non-existent field will be initialized with its default value, but deprecated fields will not be removed.
![image](https://github.com/harshkhandeparkar/tauri-settings/assets/34770591/31f925ec-0ff4-4288-a0cf-621c75f34cde)
Note that this only works at the top level, so if a new field is added under the `telemetry` object, its default will not be added.

If you need more control than that, the best way to handle this right now would be to add a `version` field yourself or check for the existence of the `telemetry` field, add its value to the settings, and save the new settings.

**Comment by Hacksore** [comment]
The merge sounds sufficient, thanks!
