### ISSUE TITLE
Settings directory is created twice if two settings files are used

### ISSUE THREAD

**Issue by dabch** [harshkhandeparkar/tauri-settings#4]
When the settings directory doesn't exist and two settings files are used, the module tries to create the settings directory twice. The second time fails, and thus the second settings file can't be created.

The error message `[Error] ERROR
Error: Uncaught (in promise): path: /home/user/.config/com.program.name/ (non recursive): File exists (os error 17)` is shown when starting the program with the directory ~/.config.program.name/ not existing. If instead the directory exists (even if it is empty), both settings files are successfully created.

This bug lead to the application crashing because one of the two settings files is unavailable at the first run after deleting the settings directory.

**Comment by harshkhandeparkar** [comment]
Could you elaborate what you mean by two settings files?

**Comment by dabch** [comment]
Sure. I have two instances of  `SettingsManager` in different modules with different filenames (let's say settings-1.json and settings-2.json) being used in different modules of my (angular) app. They both get initialized at the same time. When the application is started for the first time (i.e. the settings folder doesn't exist yet) only one of the `SettingsManager`s is initialized successfullly and the other is unedfined (and the error above is shown).

From how I understood the code of this module, there seems to be a race condition in this try-catch block: [ensure-settings-file.ts:29](https://github.com/harshkhandeparkar/tauri-settings/blob/c01f19a61569658adba00aacd5a2e076c822d0d9/src/fs/ensure-settings-file.ts#L29). Both instances of `SettingsManager` check if the folder exists, and then both try to create it. But only one can succeed of course.

I was going to try and fix this, but I haven't been able to get Typescript/Angular to accept my local copy of the module.

**Comment by harshkhandeparkar** [comment]
> From how I understood the code of this module, there seems to be a race condition in this try-catch block: [ensure-settings-file.ts:29](https://github.com/harshkhandeparkar/tauri-settings/blob/c01f19a61569658adba00aacd5a2e076c822d0d9/src/fs/ensure-settings-file.ts#L29). Both instances of SettingsManager check if the folder exists, and then both try to create it. But only one can succeed of course.

Hmm, will have to investigate. As a temporary fix, perhaps you can initialize the second `SettingsManager` once the first one has been initialized using `await` or `.then()`.

**Comment by dabch** [comment]
That's a good idea, thanks! I didn't expect you to get active so quickly, appreciate that! :)

**Comment by harshkhandeparkar** [comment]
Closing this.
